# WedSync Ultra-Stable AlertManager Configuration
# Intelligent alerting with context-aware notifications

global:
  # Default notification settings
  smtp_smarthost: 'localhost:587'
  smtp_from: 'wedsync-alerts@localhost'

# Route alerts based on severity and impact
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'development-alerts'
  
  routes:
    # Critical development disruption - immediate notification
    - match:
        severity: critical
        impact: development
      receiver: 'critical-development'
      group_wait: 0s
      repeat_interval: 5m
    
    # Performance degradation - developer notification
    - match:
        impact: productivity
      receiver: 'performance-alerts'
      group_interval: 2m
      repeat_interval: 30m
    
    # Security issues - special handling
    - match:
        impact: security
      receiver: 'security-alerts'
      repeat_interval: 1h
    
    # Code quality - development team notification
    - match:
        impact: code_quality
      receiver: 'code-quality-alerts'
      repeat_interval: 4h

receivers:
  # Default development alerts
  - name: 'development-alerts'
    webhook_configs:
      - url: 'http://wedsync-ultra:3000/api/alerts/webhook'
        send_resolved: true
        title: 'WedSync Development Alert'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Impact: {{ .Labels.impact }}
          {{ if .Annotations.action }}Action: {{ .Annotations.action }}{{ end }}
          {{ end }}

  # Critical development disruption alerts
  - name: 'critical-development'
    webhook_configs:
      # Desktop notification
      - url: 'http://localhost:8090/notify'
        send_resolved: true
        title: '🚨 CRITICAL: WedSync Development Issue'
        text: |
          {{ range .Alerts }}
          IMMEDIATE ATTENTION REQUIRED:
          {{ .Annotations.summary }}
          
          Description: {{ .Annotations.description }}
          {{ if .Annotations.action }}Automated Action: {{ .Annotations.action }}{{ end }}
          
          Time: {{ .StartsAt.Format "15:04:05 MST" }}
          {{ end }}
    
    # Auto-recovery trigger
    webhook_configs:
      - url: 'http://wedsync-auto-recovery:3000/trigger'
        send_resolved: false
        http_config:
          bearer_token: 'wedsync-auto-recovery-token'

  # Performance alerts with trending data
  - name: 'performance-alerts'
    webhook_configs:
      - url: 'http://wedsync-ultra:3000/api/alerts/performance'
        send_resolved: true
        title: '⚡ Performance Alert: {{ .GroupLabels.alertname }}'
        text: |
          Performance issue detected:
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          Impact: {{ .Annotations.description }}
          
          Trend: Check Grafana dashboard for detailed metrics
          {{ end }}

  # Security vulnerability alerts
  - name: 'security-alerts'
    webhook_configs:
      - url: 'http://wedsync-ultra:3000/api/alerts/security'
        send_resolved: true
        title: '🔒 Security Alert: {{ .GroupLabels.alertname }}'
        text: |
          Security issue detected:
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          
          Recommendation: Review and update dependencies
          {{ end }}

  # Code quality alerts
  - name: 'code-quality-alerts'
    webhook_configs:
      - url: 'http://wedsync-ultra:3000/api/alerts/code-quality'
        send_resolved: true
        title: '📊 Code Quality Alert'
        text: |
          Code quality metrics:
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}

# Alert inhibition rules
inhibit_rules:
  # Don't alert on individual container issues if Docker daemon is down
  - source_match:
      alertname: 'DockerDaemonUnhealthy'
    target_match_re:
      alertname: '.*Container.*'
    equal: ['cluster']
  
  # Don't alert on performance issues if memory pressure is critical
  - source_match:
      alertname: 'MemoryPressureHigh'
    target_match:
      impact: 'productivity'
    equal: ['instance']

# Notification templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'