# Ultra-Stable WedSync Prometheus Configuration
# Advanced monitoring with predictive alerting

global:
  scrape_interval: 5s        # High-frequency monitoring
  evaluation_interval: 10s   # Fast alert evaluation
  scrape_timeout: 5s

# Alert rules for predictive monitoring
rule_files:
  - "alert-rules.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configuration for all WedSync services
scrape_configs:
  # WedSync Application Metrics
  - job_name: 'wedsync-app'
    static_configs:
      - targets: ['wedsync-ultra:3000']
    scrape_interval: 5s
    metrics_path: '/api/metrics'
    scrape_timeout: 3s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['wedsync-watchdog:9100']
    scrape_interval: 5s

  # Container Metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['wedsync-cadvisor:8080']
    scrape_interval: 10s

  # Development Metrics
  - job_name: 'dev-metrics'
    static_configs:
      - targets: ['wedsync-dev-metrics:9091']
    scrape_interval: 5s

  # Docker Daemon Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Storage configuration for performance
storage:
  tsdb:
    retention.time: '7d'
    retention.size: '10GB'
    wal-compression: true