# Prometheus Configuration for PDF Analysis System
# WS-242: AI PDF Analysis System - Monitoring Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "wedding_alerts.yml"

scrape_configs:
  # PDF Analysis Service Metrics
  - job_name: 'pdf-analysis-service'
    static_configs:
      - targets: ['pdf-analysis:9090']
    scrape_interval: 10s
    metrics_path: /api/metrics
    params:
      format: ['prometheus']

  # Node.js Application Metrics
  - job_name: 'nodejs-metrics'
    static_configs:
      - targets: ['pdf-analysis:3000']
    metrics_path: /api/metrics/nodejs
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL Metrics  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Recording rules for PDF Analysis metrics
rule_files:
  - "/etc/prometheus/rules/*.yml"